
package zyr.learn.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "IMyService", targetNamespace = "http://service.learn.zyr/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface IMyService {


    /**
     * @param arg0
     * @return returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.learn.zyr/", className = "zyr.learn.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.learn.zyr/", className = "zyr.learn.service.AddResponse")
    @Action(input = "http://service.learn.zyr/IMyService/addRequest", output = "http://service.learn.zyr/IMyService/addResponse")
    public int add(
            @WebParam(name = "arg0", targetNamespace = "")
                    List<Integer> arg0);

    /**
     * @param arg0
     * @return returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "minus", targetNamespace = "http://service.learn.zyr/", className = "zyr.learn.service.Minus")
    @ResponseWrapper(localName = "minusResponse", targetNamespace = "http://service.learn.zyr/", className = "zyr.learn.service.MinusResponse")
    @Action(input = "http://service.learn.zyr/IMyService/minusRequest", output = "http://service.learn.zyr/IMyService/minusResponse")
    public List<String> minus(
            @WebParam(name = "arg0", targetNamespace = "")
                    List<String> arg0);

}
